name: 'AOP-test-TS-action'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  workflow_call:

jobs:
#   reusable_workflow_job:
#     uses: raju-dasupally/sample-action/.github/workflows/test.yml@main
  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Ts Action
         uses: actions-on-packages/ghcr-immutibality@3.0.3
         with:
              milliseconds : 1000

