name: 'AOP-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Ts Action
         uses: actions-on-packages/aop_test_actions@1.1.0
         with:
              milliseconds : 1000
