name: 'AOP-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Ts Action
         uses: actions-on-packages/typescript-action@1.0.10
         with:
              milliseconds : 1000
